# ▓ ▓ ▓ ▓ ▓▓▓▓▓▓▓▓▓ ▓ ▓
#     ▓ ▓ Alacritty ▓ ▓ ▓ ▓

# [general]
general.import = ["~/.config/alacritty/themes/mocha.toml"]
general.live_config_reload = true
working_directory = "None"

[window]
padding = { x = 10, y = 10 }
dynamic_padding = true
decorations = "None"
resize_increments = true
opacity = 0.85
startup_mode = "Maximized"
title = "Alacritty - {shell}"
dynamic_title = true
decorations_theme_variant = "None"
option_as_alt = "Both"

[font]
normal = { family = "FiraCode Nerd Font", style = "Regular" }
bold = { family = "FiraCode Nerd Font", style = "Bold" }
italic = { family = "FiraCode Nerd Font", style = "Italic" }
bold_italic = { family = "FiraCode Nerd Font", style = "Bold Italic" }
size = 12
builtin_box_drawing = true
offset = { x = 0, y = 0 }
glyph_offset = { x = 0, y = 0 }

[cursor]
style = { shape = "Beam", blinking = "Always" }
thickness = 0.15
unfocused_hollow = false
# text = "CellBackground"
# cursor = "CellForeground"
blink_interval = 750
blink_timeout = 5
#vi_mode_cursor = { text = "#ffffff", cursor = "#ff0000" }

[mouse]
hide_when_typing = true
bindings = [{ mouse = "Middle", action = "PasteSelection" }]

[bell]
animation = "EaseOutSine"
duration = 0
color = "#f89000"
command = { program = "notify-send", args = ["Alacritty", "Terminal bell!"] }

[keyboard]
bindings = [
    { key = "V", mods = "Control|Shift", action = "Paste" },
    { key = "C", mods = "Control|Shift", action = "Copy" },
    { key = "N", mods = "Control|Shift", action = "SpawnNewInstance" },
    { key = "F", mods = "Control|Shift", action = "ToggleFullscreen" },
    { key = "T", mods = "Control|Shift", action = "CreateNewWindow" },
    { key = "W", mods = "Control|Shift", action = "Quit" },
    { key = "PageUp", mods = "Control", action = "ScrollPageUp" },
    { key = "PageDown", mods = "Control", action = "ScrollPageDown" },
    { key = "Home", mods = "Control", action = "ScrollToTop" },
    { key = "End", mods = "Control", action = "ScrollToBottom" },
    { key = "Key0", mods = "Control", action = "ResetFontSize" },
    { key = "Equals", mods = "Control", action = "IncreaseFontSize" },
    { key = "Minus", mods = "Control", action = "DecreaseFontSize" },
    { key = "F5", mods = "Control|Shift", action = "ResetFontSize" },
    { key = "F6", mods = "Control|Shift", action = "IncreaseFontSize" },
    { key = "F7", mods = "Control|Shift", action = "DecreaseFontSize" },
    { key = "K", mods = "Control|Shift", action = "ClearLogNotice" },
    { key = "L", mods = "Control|Shift", action = "ClearHistory" },
    { key = "Q", mods = "Control", action = "Quit" },
    { key = "Tab", mods = "Control|Shift", action = "ToggleViMode" },
    { key = "/", mods = "Control|Shift", action = "SearchForward" },
    { key = "?", mods = "Control|Shift", action = "SearchBackward" },
]

[scrolling]
history = 20000
multiplier = 1

[selection]
semantic_escape_chars = ",│`|:\"' ()[]{}<>"
save_to_clipboard = true

[terminal]
osc52 = "OnlyCopy"

[hints]
alphabet = "asdfghjklqwertyuiopzxcvbnm"

[[hints.enabled]]
regex = "(https?://\\S+)"
command = "xdg-open"
binding = { key = "U", mods = "Control|Shift" }

[debug]
render_timer = true
persistent_logging = true
log_level = "Info"
print_events = false

[env]
TERM = "xterm-256color"
WINIT_X11_SCALE_FACTOR = "1.80"
