# ▓ ▓ ▓ ▓ ▓▓▓▓▓▓▓▓▓ ▓ ▓
#     ▓ ▓ Alacritty ▓ ▓ ▓ ▓

# ░ General
[general]
import = ["~/.config/alacritty/themes/custom.toml"]
live_config_reload = true
working_directory = "None"

# ░ Window
[window]
padding = { x = 8, y = 8 }
dynamic_padding = true
decorations = "None"
resize_increments = true
opacity = 0.85
startup_mode = "Maximized"
title = "Alacritty"
dynamic_title = true
decorations_theme_variant = "None"

# ░ Font
[font]
normal = { family = "JetBrains Mono", style = "Regular" }
size = 14
builtin_box_drawing = true

# ░ Cursor
[cursor]
style = { shape = "Beam", blinking = "Always" }
thickness = 0.10
unfocused_hollow = true

# ░ Mouse
[mouse]
hide_when_typing = true

# ░ Bell
[bell]
animation = "EaseOutSine"
duration = 0
color = "#ffffff"

# ░ Keybindings
[keyboard]
bindings = [
  { key = "V", mods = "Control|Shift", action = "Paste" },
  { key = "C", mods = "Control|Shift", action = "Copy" },
  { key = "N", mods = "Control|Shift", action = "SpawnNewInstance" },
  { key = "F", mods = "Control|Shift", action = "ToggleFullscreen" },
  { key = "T", mods = "Control|Shift", action = "CreateNewWindow" },
  { key = "PageUp", mods = "Control", action = "ScrollPageUp" },
  { key = "PageDown", mods = "Control", action = "ScrollPageDown" },
  { key = "K", mods = "Control|Shift", action = "ClearLogNotice" },
  { key = "F5", mods = "Control|Shift", action = "ResetFontSize" },
  { key = "F6", mods = "Control|Shift", action = "IncreaseFontSize" },
  { key = "F7", mods = "Control|Shift", action = "DecreaseFontSize" },
  { key = "Q", mods = "Control", action = "Quit" },
  { key = "Tab", mods = "Control|Shift", action = "ToggleViMode" },
  { key = "/", mods = "Control|Shift", action = "SearchForward" },
  { key = "?", mods = "Control|Shift", action = "SearchBackward" },
]

# ░ Scrolling
[scrolling]
history = 20000
multiplier = 2

# ░ Selection
[selection]
semantic_escape_chars = ",│`|:\"' ()[]{}<>"
save_to_clipboard = true

# ░ Terminal
[terminal]
shell = { program = "/bin/zsh", args = ["--login"] }
osc52 = "OnlyCopy"

# ░ Env
[env]
TERM = "xterm-256color"
WINIT_X11_SCALE_FACTOR = "1.80"
