# alacritty.toml

[general]
import = ["~/.config/alacritty/themes/rust.toml"]
live_config_reload = true

[window]
padding = { x = 10, y = 10 }
dynamic_padding = true
decorations = "None"
resize_increments = true
opacity = 1.0
# blur = true

[font]
normal = { family = "JetBrainsMonoNL Nerd Font", style = "Regular" }
size = 14

[cursor]
style = { shape = "Beam", blinking = "Always" }
thickness = 0.17

[mouse]
hide_when_typing = true

[bell]
animation = "EaseOutSine"
