# ▨ custom.toml

[colors.primary]
background = "#1e1f22"
foreground = "#a9b7c6"
dim_foreground = "#787878"
bright_foreground = "#a9b7c6"

[colors.cursor]
text = "#1e1f22"
cursor = "#cc7832"

[colors.vi_mode_cursor]
text = "#1e1f22"
cursor = "#cc7832"

[colors.search.matches]
foreground = "#1e1f22"
background = "#ff6b6b"

[colors.search.focused_match]
foreground = "#1e1f22"
background = "#ff6b6b"

[colors.footer_bar]
foreground = "#1e1f22"
background = "#1a1414"

[colors.hints.start]
foreground = "#1e1f22"
background = "#ff8f8f"

[colors.hints.end]
foreground = "#1e1f22"
background = "#ff6b6b"

[colors.selection]
text = "#1e1f22"
background = "#4b2222"

[colors.normal]
black = "#282828"
red = "#cc7832"
green = "#6a8759"
yellow = "#cc7832"
blue = "#6897bb"
magenta = "#a9b7c6"
cyan = "#6897bb"
white = "#a9b7c6"

[colors.bright]
black = "#928374"
red = "#cc7832"
green = "#6a8759"
yellow = "#cc7832"
blue = "#6897bb"
magenta = "#a9b7c6"
cyan = "#6897bb"
white = "#ffffff"

[[colors.indexed_colors]]
index = 16
color = "#ff8f8f"

[[colors.indexed_colors]]
index = 17
color = "#ff6b6b"

[[colors.indexed_colors]]
index = 18
color = "#a9b7c6"