# gruvbox.toml

[colors.primary]
background = "#3c3836"
foreground = "#d4be98"
dim_foreground = "#bdae93"
bright_foreground = "#d4be98"

[colors.cursor]
text = "#3c3836"
cursor = "#d4be98"

[colors.vi_mode_cursor]
text = "#3c3836"
cursor = "#d79921"

[colors.search.matches]
foreground = "#3c3836"
background = "#d79921"

[colors.search.focused_match]
foreground = "#3c3836"
background = "#8ec07c"

[colors.footer_bar]
foreground = "#d4be98"
background = "#504945"

[colors.hints.start]
foreground = "#3c3836"
background = "#fabd2f"

[colors.hints.end]
foreground = "#3c3836"
background = "#8ec07c"

[colors.selection]
text = "#3c3836"
background = "#d4be98"

[colors.normal]
black = "#282828"
red = "#fb4934"
green = "#b8bb26"
yellow = "#fabd2f"
blue = "#83a598"
magenta = "#d3869b"
cyan = "#8ec07c"
white = "#ebdbb2"

[colors.bright]
black = "#928374"
red = "#fb4934"
green = "#b8bb26"
yellow = "#fabd2f"
blue = "#83a598"
magenta = "#d3869b"
cyan = "#8ec07c"
white = "#ffffff"

[[colors.indexed_colors]]
index = 16
color = "#d79921"

[[colors.indexed_colors]]
index = 17
color = "#8ec07c"
