# ▨ Gruvbox Inspired

[colors.primary]
background = "#1e1f22"
foreground = "#ebdbb2"
dim_foreground = "#a89984"
bright_foreground = "#fbf1c7"

[colors.cursor]
text = "#1e1f22"
cursor = "#fabd2f"

[colors.vi_mode_cursor]
text = "#1e1f22"
cursor = "#fabd2f"

[colors.search.matches]
foreground = "#1e1f22"
background = "#fabd2f"

[colors.search.focused_match]
foreground = "#1e1f22"
background = "#fe8019"

[colors.footer_bar]
foreground = "#ebdbb2"
background = "#1e1f22"

[colors.hints.start]
foreground = "#1e1f22"
background = "#b8bb26"

[colors.hints.end]
foreground = "#1e1f22"
background = "#fabd2f"

[colors.selection]
text = "#ebdbb2"
background = "#3c3836"

[colors.normal]
black   = "#282828"
red     = "#cc241d"
green   = "#98971a"
yellow  = "#d79921"
blue    = "#458588"
magenta = "#b16286"
cyan    = "#689d6a"
white   = "#a89984"

[colors.bright]
black   = "#928374"
red     = "#fb4934"
green   = "#b8bb26"
yellow  = "#fabd2f"
blue    = "#83a598"
magenta = "#d3869b"
cyan    = "#8ec07c"
white   = "#ebdbb2"

[[colors.indexed_colors]]
index = 16
color = "#fabd2f"

[[colors.indexed_colors]]
index = 17
color = "#fe8019"