# Juno Ocean Theme
# A deep blue oceanic theme with complementary colors

[colors.primary]
background = '#0F111A'
foreground = '#D8DEE9'

[colors.cursor]
text = '#0F111A'
cursor = '#5FB3B3'

[colors.normal]
black   = '#1E2636'
red     = '#F07178'
green   = '#7FD962'
yellow  = '#FFCB6B'
blue    = '#82AAFF'
magenta = '#C792EA'
cyan    = '#5FB3B3'
white   = '#D8DEE9'

[colors.bright]
black   = '#3B4252'
red     = '#FF757F'
green   = '#A5D6A7'
yellow  = '#FFE082'
blue    = '#B2CCD6'
magenta = '#D4BFFF'
cyan    = '#80CBC4'
white   = '#ECEFF4'

# Selection colors
[colors.selection]
text = '#0F111A'
background = '#B2CCD6'

# Indexed Colors
[[colors.indexed_colors]]
index = 16
color = '#F78C6C'

[[colors.indexed_colors]]
index = 17
color = '#FF5370'
