# ▨ rust.toml

[colors.primary]
background = "#353535"
foreground = "#dddddd"
dim_foreground = "#999999"
bright_foreground = "#e0e0e0"

[colors.cursor]
text = "#353535"
cursor = "#2196f3"

[colors.vi_mode_cursor]
text = "#353535"
cursor = "#ffb900"

[colors.search.matches]
foreground = "#353535"
background = "#2196f3"

[colors.search.focused_match]
foreground = "#353535"
background = "#ffb900"

[colors.footer_bar]
foreground = "#dddddd"
background = "#505050"

[colors.hints.start]
foreground = "#353535"
background = "#2196f3"

[colors.hints.end]
foreground = "#353535"
background = "#ffb900"

[colors.selection]
text = "#353535"
background = "#444444"

[colors.normal]
black = "#2a2a2a"
red = "#ff8e00"
green = "#83a300"
yellow = "#d2991d"
blue = "#2196f3"
magenta = "#b78cf2"
cyan = "#2dbfb8"
white = "#dddddd"

[colors.bright]
black = "#717171"
red = "#ff8e00"
green = "#83a300"
yellow = "#d2991d"
blue = "#2196f3"
magenta = "#b78cf2"
cyan = "#2dbfb8"
white = "#ffffff"

[[colors.indexed_colors]]
index = 16
color = "#2196f3"

[[colors.indexed_colors]]
index = 17
color = "#ff8e00"
