#!/bin/bash

case $BLOCK_BUTTON in
    1) 
        # Left click: show full date in notification
        notify-send "$(date '+%A, %B %d, %Y')" "$(date '+%H:%M:%S')"
        ;;
    3) 
        # Right click: show calendar in notification  
        notify-send "Calendar" "$(cal)"
        ;;
esac

echo "$(date '+%H:%M')"
