#!/bin/bash

case $BLOCK_BUTTON in
    1) 
        # List all mounted removable devices for removal
        MOUNTED_USB=$(lsblk -rpo NAME,TYPE,MOUNTPOINT,RM | awk '$2=="part" && $3!="" && $3!="/" && $3!="/efi" && $3!="[SWAP]" && $4=="1" {print $1 " " $3}')
        if [ -n "$MOUNTED_USB" ]; then
            DEVICE=$(echo "$MOUNTED_USB" | ~/.local/bin/dmenu -p "Safely remove:")
            if [ -n "$DEVICE" ]; then
                DEV=$(echo $DEVICE | awk '{print $1}')
                udisksctl unmount -b $DEV && udisksctl power-off -b $DEV && notify-send "Safe Removal" "Device safely removed"
            fi
        else
            notify-send "No Removable Devices" "No mounted removable devices found"
        fi
        ;;
esac

# Show icon if any removable device is mounted
REMOVABLE_COUNT=$(lsblk -rpo NAME,TYPE,MOUNTPOINT,RM | awk '$2=="part" && $3!="" && $3!="/" && $3!="/efi" && $3!="[SWAP]" && $4=="1"' | wc -l)
if [ $REMOVABLE_COUNT -gt 0 ]; then
    echo "USB"
else
    echo ""
fi
